export const manufacturers = [
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Maserati",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "MINI",
    "Mitsubishi",
    "Nissan",
    "Porsche",
    "Ram",
    "Rolls-Royce",
    "Subaru",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "Polestar",
    "Genesis",
    "Lucid"
];

export const CarTypes = [
    "Sedan",
    "SUV (Sport Utility Vehicle)",
    "Coupe",
    "Convertible",
    "Hatchback",
    "Station Wagon",
    "Pickup Truck",
    "Minivan",
    "Crossover",
    "Sports Car",
    "Luxury Car",
    "Electric Car",
    "Hybrid Car",
    "Compact Car",
    "Microcar",
    "Off-Road Vehicle",
    "Muscle Car",
    "Roadster",
    "Supercar",
    "Vintage Car",
    "Classic Car",
    "4x4 (Four-Wheel Drive)",
    "Compact SUV",
    "Midsize SUV",
    "Full-Size SUV",
    "Compact Pickup Truck",
    "Full-Size Pickup Truck",
    "Subcompact Car",
    "Eco-Friendly Car",
    "Family Car",
    "Executive Car",
    "Limousine",
    "Police Car",
    "Taxi",
    "Ambulance",
    "Fire Truck",
    "Ice Cream Truck",
    "Food Truck",
    "RV (Recreational Vehicle)",
    "Camper Van",
    "Hearse",
    "Armored Car",
    "Vintage Truck",
    "Trolley Car",
    "Amphibious Car",
    "Dune Buggy",
    "Race Car",
    "Rally Car",
    "Dragster",
    "Monster Truck"
]

export const SalaryList = [
    "1,000 - 5,000 THB",
    "5,000 - 10,000 THB",
    "10,000 - 20,000 THB",
    "20,000 - 30,000 THB",
    "30,000 - 50,000 THB",
    "50,000 - 75,000 THB",
    "75,000 - 100,000 THB",
    "100,000 - 150,000 THB",
    "150,000 - 200,000 THB",
    "200,000 - 250,000 THB",
    "250,000 - 300,000 THB",
    "300,000 - 400,000 THB",
    "400,000 - 500,000 THB",
    "500,000 - 750,000 THB",
    "750,000 - 1,000,000 THB",
    "1,000,000+ THB"
]