/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alucard2077 (https://sketchfab.com/Alucard2077)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/la-ferrari-2013-3d8a15d607b548ee901c5ffb3927cd70
Title: La Ferrari 2013
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function FerrariModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/canvas/ferrari/ferrari.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="2013_Ferrari_LaFerrari_fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="FerrariLaFerrari"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                  </group>
                </group>
                <group name="Empty" position={[0, 0, 24.779]} scale={0} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/canvas/ferrari/ferrari.glb");