import '@/style/globals.css'
import Footer from '@/components/Footer'
import { Navbar } from '@/components/Navbar'
import { ThemeProvider } from '@/components/theme-provider'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Righteous } from 'next/font/google'
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const righteous = Righteous({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-righteous"
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen', righteous.variable)}>
        <ThemeProvider attribute="class" defaultTheme="light" >
          <Navbar />
          <main className='flex-1'>
            {children}
            <SpeedInsights />
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
