import { Navbar } from '@/components/Navbar'
import { ThemeProvider } from '@/components/theme-provider'
import { cn } from '@/lib/utils'
import '@/style/globals.css'
import type { Metadata } from 'next'
import { Righteous } from 'next/font/google'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const righteous = Righteous({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-righteous"
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen', righteous.variable)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>

          <Navbar />
          <main className='flex-1'>
            {children}
          </main>

        </ThemeProvider>
      </body>
    </html>
  )
}
